export const cardData = [
    {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blsdlfjlasjfl;asjfdl;ksajdfl;jkas;ldfjkasl;kdfjsal;fdjka;lkjfog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    }, {
        image: '/image.png',
        category: 'Blog',
        title: 'Sample Blog Title',
        description: 'This is a sample blog description that may be longer than eighty words. If it exceeds that length, it will be truncated and will show an ellipsis.',
        author: 'Shubham Patodia',
        date: 'September 29, 2024',
    },
];

export const smallCard= [
    { title: "Card 1", description: "This is the description for card 1." },
    { title: "Card 2", description: "This is the description for card 2, which is a bit longer to demonstrate truncation if needed." },
    { title: "Card 3", description: "Short description." },
    { title: "Card 1", description: "This is the description for card 1." },
    { title: "Card 2", description: "This is the description for card 2, which is a bit longer to demonstrate truncation if needed." },
    { title: "Card 3", description: "Short description." }, { title: "Card 1", description: "This is the description for card 1." },
    { title: "Card 2", description: "This is the description This is the description This is the description This is the description This is the description This is the description This is the description This is the description This is the description This is the description for card 2, which is a bit longer to demonstrate truncation if needed." },
    { title: "Card 3", description: "Short description." }, { title: "Card 1", description: "This is the description for card 1." },
    { title: "Card 2", description: "This is the description for card 2, which is a bit longer to demonstrate truncation if needed." },
    { title: "Card 3", description: "Short description." },
  ];